### PR TITLE
Switch to Gradle, added Material Design elements

### PR DESCRIPTION
**Pull request by TheDiamondYT1**
I had to switch to gradle to implement the AppCompat support library, but trust me its worth it.

You dont have to give me credit if you don't want too.

**Images:** http://imgur.com/a/VKojP

### CODE REVIEW

**Comment by scar45** [comment]
Thanks! This webviewer certainly needed some updating-love, but life has been crazy for me lately. Give me a bit to review and (most likely) accept the pull-request, of course giving you credit as it's deserved!

**Comment by TheDiamondYT1** [comment]
Thanks! =)

**Comment by TheDiamondYT1** [comment]
any progress?

**Comment by scar45** [comment]
Done and done. I built and tested successfully after compiling with JDK 8 and changing a line in AndroidManifest.xml relating to the theme used. Previous runtime error before the theme line change was:

`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.scar45.aokp.co.webviewer/com.scar45.aokp.co.webviewer.MainActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.`

Thank you @TheDiamondYT1 !

**Pull request merged**
